### ISSUE TITLE
Value not in range: -1 When I try to get amount from a textEditingController

### ISSUE THREAD

**Issue by muhib349** [sanjidbillah/aamarpay#2]
In **transaction amount** when I use hardcoded value it works fine but when I try to get data from a texteditingcontroller it gives me exception 
`Unhandled Exception: RangeError: Value not in range: -1
E/flutter (26283): #0      _StringBase.substring (dart:core-patch/string_patch.dart:393:7)
E/flutter (26283): #1      _AamarpayDataState.getPayment (package:aamarpay/src/aamarpaydata.dart:155:14)`
I used this line to get data `transactionAmount: _rechargeAmountController.text,`
Please have a look.

**Comment by sanjidbillah** [comment]
Did you use your controller in textfield?

**Comment by muhib349** [comment]
Yes, of course.

**Comment by sanjidbillah** [comment]
Try this code for temporary solution..

```
 TextField(
          controller: controller,
          onChanged: (v) {
            setState(() {});
          },
        ),
```

**Comment by muhib349** [comment]
It doesn't work for me.

**Comment by muhib349** [comment]
### Please see this scenario
```
import 'dart:math';

import 'package:aamarpay/aamarpay.dart';
import 'package:flutter/material.dart';

void main(){
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Test App",
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  TextEditingController _amountController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Demo App"),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Padding(
              padding: EdgeInsets.symmetric(vertical: 20),
              child: TextFormField(
                controller: _amountController,
                keyboardType: TextInputType.numberWithOptions(),
                decoration: InputDecoration(
                  icon: Icon(Icons.money),
                  hintText: 'Amount',
                  border: const OutlineInputBorder(),
                ),
              ),
            ),
            AamarpayData(
              returnUrl: (url) {
              },
              isLoading: (v) {},
              paymentStatus: (status) {
                print(status);
                if (status == "success") {
                } else if (status == "fail") {
                } else if (status == "cancel") {
                }
              },
              cancelUrl: "example.com/payment/cancel",
              successUrl: "example.com/payment/confirm",
              failUrl: "example.com/payment/fail",
              customerEmail: "masumbillahsanjid@gmail.com",
              customerMobile: "01834760591",
              customerName: "Masum Billah Sanjid",
              signature: "dbb74894e82415a2f7ff0ec3a97e4183",
              storeID: "aamarpaytest",
              transactionAmount: _amountController.text,
              transactionID: "${generateRandomString(20)}",
              description: "asgsg",
              url: "https://sandbox.aamarpay.com",
              child: _getPayNow(),
            )
          ],
        ),
      ),
    );
  }

  Widget _getPayNow() {
    return Container(
        padding: EdgeInsets.symmetric(
            horizontal: 12,
            vertical: 6),
        margin: EdgeInsets.only(right: 10, bottom: 5),
        decoration: BoxDecoration(
          color: Color(0xFF8212F8),
          //borderRadius: BorderRadius.circular(6),
        ),
        child: Text(
          "Pay now",
          style: TextStyle(color: Colors.white),
        ));
  }

  String generateRandomString(int len) {
    var r = Random();
    const _chars = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
    return List.generate(len, (index) => _chars[r.nextInt(_chars.length)]).join();
  }
}
```

**Comment by sanjidbillah** [comment]
```
import 'package:flutter/material.dart';
import 'package:aamarpay/aamarpay.dart';

void main() {
  runApp(MaterialApp(
    home: MyPay(),
  ));
}

class MyPay extends StatefulWidget {
  @override
  _MyPayState createState() => _MyPayState();
}

class _MyPayState extends State<MyPay> {
  bool isLoading = false;
  var controller = TextEditingController();
  var myamount;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        TextField(
          controller: controller,
          onChanged: (v) {
            myamount = v;
            setState(() {});
          },
        ),
      
        Center(
          child: AamarpayData(
              returnUrl: (url) {
                print(url);
              },
              isLoading: (v) {
                setState(() {
                  isLoading = v;
                });
              },
              paymentStatus: (status) {
                print(status);
              },
              cancelUrl: "example.com/payment/cancel",
              successUrl: "example.com/payment/confirm",
              failUrl: "example.com/payment/fail",
              customerEmail: "masumbillahsanjid@gmail.com",
              customerMobile: "01834760591",
              customerName: "Masum Billah Sanjid",
              signature: "dbb74894e82415a2f7ff0ec3a97e4183",
              storeID: "aamarpaytest",
              transactionAmount: "${myamount}",
              transactionID: "wtwtwt",
              description: "asgsg",
              url: "https://sandbox.aamarpay.com",
              child: isLoading
                  ? Center(
                      child: CircularProgressIndicator(),
                    )
                  : Container(
                      color: Colors.orange,
                      height: 50,
                      child: Center(
                          child: Text(
                        "Payment",
                        style: TextStyle(
                            fontWeight: FontWeight.bold, color: Colors.white),
                      )),
                    )),
        ),
      ],
    ));
  }
}

```

Try with this brother

**Comment by jobayedsumon** [comment]
This issue is still there!
Please provide a solution

**Comment by sanjidbillah** [comment]
When you need to pass amount by TextEditingController,
use transactionAmountFromTextField instead of transactionAmount
